# Generated by Django 4.2.4 on 2023-08-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tax_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxationscheme",
            name="tax_rate",
            field=models.PositiveIntegerField(),
        ),
    ]
